version: '3.8'

networks:
  mynet:
    driver: bridge

volumes:
  db_data:

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: micro_db
    networks:
      - mynet
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  query-service:
    image: ion21/query-service:09.03.2024.09.43.18
    networks:
      - mynet
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"

  command-service:
    image: ion21/command-service:01.04.2024.11.44.42
    networks:
      - mynet
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy

  nserver-service:
    image: ion21/server-service:02.04.2024.06.53.01
    networks:
      - mynet
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy


  edge:
    image: ion21/gateway-service:13.04.2024.15.33.28
    networks:
      - mynet
    ports:
      - "5000:5000"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - nserver-service


  client:
    image: ion21/client-service:13.04.2024.15.32.12
    networks:
      - mynet
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_PATH_TO=development

    depends_on:
      - edge