version: '3.8'

networks:
  mynet:
    driver: bridge

volumes:
  db_data:

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: micro_db
    networks:
      - mynet
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  query-service:
    image: ion21/query-service:09.03.2024.09.43.18
    networks:
      - mynet
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"

  command-service:
    image: ion21/command-service:10.03.2024.17.14.43
    networks:
      - mynet
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy

  nserver-service:
    image: ion21/nserver-service:09.03.2024.08.05.03
    networks:
      - mynet
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy


  edge:
    image: ion21/gateway-service:09.03.2024.10.04.30
    networks:
      - mynet
    ports:
      - "5000:5000"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - nserver-service


  client:
    image: ion21/client-service:09.03.2024.10.31.58
    networks:
      - mynet
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

    depends_on:
      - edge