name: CD - Deploy Docker Compose

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: List files in the root of the repository
        run: |
            pwd
            ls -la


      - name: Deploy to EC2
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no ./docker-compose.yaml ec2-user@${{ env.EC2_INSTANCE_IP }}:/home/ec2-user/scripts/docker-compose.yaml
          ssh -o StrictHostKeyChecking=no ec2-user@${{ env.EC2_INSTANCE_IP }} "\
            cd /home/ec2-user/scripts/ && ./init.sh && \
            CONTAINERS=$(podman container ls -aq) && \
            if [ ! -z \"$CONTAINERS\" ]; then \
            podman container stop $CONTAINERS || true; \
            podman container rm $CONTAINERS || true; \
            fi; \
            echo 'Starting new containers...'; \
            podman-compose up -d; \
            echo 'Deployment completed successfully.'"
        env:
            EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
            EC2_INSTANCE_IP: 34.247.255.42
