name: CD - Deploy Docker Compose

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
#      - name: List files in the root of the repository
#        run: |
#            pwd
#            ls -la
#      - name: Find and echo the path of docker-compose.yaml
#        run: |
#            FILE_PATH=$(find . -type f -name "docker-compose.yaml")
#            echo "Path of the docker-compose.yaml file: $FILE_PATH"
      - name: Deploy to EC2
        run: |
            sudo apt-get update
            sudo apt-get install -y ssh
            mkdir -p ~/.ssh
            echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
#            echo "Flag2"
#            ls -la
#            pwd
#            echo "Flag3"
#            sudo find / -type f -name "docker-compose.yaml"
#            echo "Flag4"
            scp -v -o StrictHostKeyChecking=no ./docker-compose.yaml ubuntu@${{ env.EC2_INSTANCE_IP }}:/home/doker/docker-compose.yaml
            ssh -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_INSTANCE_IP }} "cd /home/doker/ && docker-compose up -d"
        env:
            EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
            EC2_INSTANCE_IP: 3.252.249.66
